### ISSUE TITLE
Allow colon in class names

### ISSUE THREAD

**Issue by bb** [vitallium/tree-sitter-haml#5]
The official HAML parser allows a few characters which are not yet supported here, e.g. colon `:` which is heavily used in tailwindcss.

Comparing
https://github.com/haml/haml/blob/3841f56a8005bebcd89ee11de6afcd34f1f4abcb/lib/haml/parser.rb#L589

```ruby
 list.scan(/([#.])([-:_a-zA-Z0-9\@]+)/) do |type, property|
```

to https://github.com/vitallium/tree-sitter-haml/blob/91e1f9a3bc2410930bb105dca158c280fee0271e/src/grammar.json#L301
```json
      "value": "[_a-z0-9\\-]*[_a-zA-Z][_a-zA-Z0-9\\-]*",
```

it looks like HAML itself allows way more than what would practically be useful, but the current tree sitter grammar is at least missing colon which would be very useful for lines like `.mx-2.sm:mx-5`.

Please add colon to the grammar and -- if you like -- also `@` or even update the rules to match official HAML, even though they're quite permissive.

**Comment by vitallium** [comment]
@bb Hi, thanks for opening this issue. I opted to reuse the regex from HAML implementation to support both `:` and `@` symbols in ID and CSS class names. Landed it in https://github.com/vitallium/tree-sitter-haml/commit/1d3766b84005009febd5471be561b876f1db503d Let me know if that works for you. Thanks!

**Comment by bb** [comment]
That's great, thanks. Thank you for also creating the PR in zed-haml!
