### ISSUE TITLE
`filter_body` is a bit too eager

### ISSUE THREAD

**Issue by davidcornu** [vitallium/tree-sitter-haml#6]
![CleanShot 2024-11-07 at 10 01 35](https://github.com/user-attachments/assets/75893337-24ee-4db3-830f-bd6cd1174640)

For syntax like

```haml
  :css
    body { padding: 0; }
  - other_ruby_code
```

the `filter_body` AST node will extend all the way to the end of `other_ruby_code`.

However, with an element

```haml
  :css
    body { padding: 0; }
  %foo
```

it will correctly end at the end of `}`

**Comment by vitallium** [comment]
Aha, I see. I was looking at your example with `- other_ruby_code` and wondered why it fails since we have the same test case but I've managed to figure out the correct snapshot:

```
:css
  body { padding: 0; }

- other_ruby_code

```

Notice the blank line right after the filter, it breaks the parsing. I suspect that could lead to other parsing errors.

**Comment by vitallium** [comment]
Should be fixed in https://github.com/vitallium/tree-sitter-haml/commit/f99259f8a2e6600f5cd5f87b42648db2519e6f73

**Comment by davidcornu** [comment]
Thanks! I'll bump the extension when I get a chance.

**Comment by vitallium** [comment]
Found another example where `filter` capturing is failing:

```
= javascript_tag nonce: true do
  :javascript
    const { namespace: sp_namespace, hostname: sp_hostname, ...snowplowOptions } = #{raw(Gitlab::Tracking.snowplow_options.to_json)};

    window.snowplow('newTracker',
      sp_namespace,
      sp_hostname,
      snowplowOptions
    );

    window.snowplow('flushBuffer');

    window.snowplowContext = {}
```

Renders as:

![CleanShot 2024-11-18 at 18 48 26@2x](https://github.com/user-attachments/assets/3e4276a3-58d7-4d64-9966-b2b45103c01b)

**Comment by vitallium** [comment]
Should be fixed in https://github.com/vitallium/tree-sitter-haml/commit/58ea761f7375e46516e8fca246302377d52f94ca

**Comment by vitallium** [comment]
# Case 1

```
  :css
    body { padding: 0; }
  - other_ruby_code
```

**Result:**

![CleanShot 2024-11-21 at 19 23 39@2x](https://github.com/user-attachments/assets/318aad71-2b20-4444-a2cf-93a4f6444cd7)

# Case 2

```
!!!
%body
  :css
    body { padding: 0; }

  - other_ruby_code
```

**Result**

![CleanShot 2024-11-21 at 19 24 22@2x](https://github.com/user-attachments/assets/f3f41525-c8f8-4f8e-8f81-ef90b8fe7bf1)

# Case 3

```
= javascript_tag nonce: true do
  :javascript
    const { namespace: sp_namespace, hostname: sp_hostname, ...snowplowOptions } = #{raw(Gitlab::Tracking.snowplow_options.to_json)};

    window.snowplow('newTracker',
      sp_namespace,
      sp_hostname,
      snowplowOptions
    );

    window.snowplow('flushBuffer');

    window.snowplowContext = {}
```

**Result**

![CleanShot 2024-11-21 at 19 24 51@2x](https://github.com/user-attachments/assets/acf02f5b-76bb-47aa-9e53-ac6524265e63)

**Comment by vitallium** [comment]
@davidcornu can you please also check cases above or any other case to confirm that the issue is resolved? Thanks!

**Comment by davidcornu** [comment]
Will do!

**Comment by davidcornu** [comment]
@vitallium with `5dedefd955eaaadec309357879a46edf932945cf` the examples you outlined work as expected and additional futzing around hasn't yielded new issues. Calling this one good 👍.
